on:
  push:
    tags:
      - 'v*'
      - 'key-share-v*'
      - 'cggmp21-keygen-v*'
      - 'paillier-zk-v*'
  workflow_dispatch:

name: Publish

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  publish-cggmp21:
    name: Publish cggmp21
    environment: crates.io
    runs-on: ubuntu-latest
    if: >-
      github.ref_type == 'tag'
      && startsWith(github.ref_name, 'v')
    steps:
    - uses: actions/checkout@v3
    - run: cargo publish -p cggmp21
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}

  publish-key-share:
    name: Publish key-share
    environment: crates.io
    runs-on: ubuntu-latest
    if: >-
      github.ref_type == 'tag'
      && startsWith(github.ref_name, 'key-share-v')
    steps:
    - uses: actions/checkout@v3
    - run: cargo publish -p key-share
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}

  publish-cggmp21-keygen:
    name: Publish cggmp21-keygen
    environment: crates.io
    runs-on: ubuntu-latest
    if: >-
      github.ref_type == 'tag'
      && startsWith(github.ref_name, 'cggmp21-keygen-v')
    steps:
    - uses: actions/checkout@v3
    - run: cargo publish -p cggmp21-keygen
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}

  publish-paillier-zk:
    name: Publish paillier-zk
    environment: crates.io
    runs-on: ubuntu-latest
    if: >-
      github.ref_type == 'tag'
      && startsWith(github.ref_name, 'paillier-zk-v')
    steps:
    - uses: actions/checkout@v3
    - run: cargo publish -p paillier-zk
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}
